# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siauser',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
