# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siauser',
            name='card_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siauser',
            name='cvv_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siauser',
            name='expiration_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siauser',
            name='expiration_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='siauser',
            name='name_on_card',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
