# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20161006_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(max_length=200, null=True)),
                ('to_airport', models.CharField(max_length=200, null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SIAUser')),
            ],
        ),
    ]
