# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attractionticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attractionticket',
            name='price',
        ),
        migrations.AddField(
            model_name='attractionticket',
            name='activityId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attractionticket',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attractionticket',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
