# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20161007_1955'),
        ('bookings', '0006_auto_20161007_1946'),
    ]

    operations = [
    ]
